accounts:
  - name: arivano
    coins: ["20000imi", "200000000stake"]
  - name: shiy
    coins: ["10000imi", "100000000stake"]
validator:
  name: arivano
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: shiy
  coins: ["5imi", "100000stake"]
